spring.application.name=web2

# port number
# ???? 8080 ??
server.port=9999

#Context Path
server.servlet.context-path=/

#Log Level
#error > warn > info > debug > trace
# info ? ???
logging.level.root=info
logging.level.net.datasa.web1=debug

